.deploy: &deploy
  stage: deploy
  script:
    - npm install --production
    - npm run build
    - pm2 restart project-name

.deploy:staging:
  <<: *deploy
  environment:
    name: staging
    url: project-name.int.daftup.com
  only:
    - master

.deploy:production:
  <<: *deploy
  environment:
    name: production
    url: project-name.com
  only:
    - production
