.deploy: &deploy
  stage: deploy
  script:
    - yarn install
    - yarn export

.deploy:staging:
  <<: *deploy
  variables:
    APPLICATION_ENV: staging
    NODE_ENV: production
  environment:
    name: staging
    url: https://project-name.int.daftup.com
  tags:
    - deployment-stg
  only:
    - master
