image: node:alpine

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm i
    - npm run test-ci
    - npm run lint

.before_deploy: &before_deploy
  - npm i
  - apk update && apk upgrade
  - apk add git openssh bash
  - eval $(ssh-agent -s)
  - ssh-add

deploy_staging:
  stage: deploy
  before_script: *before_deploy
  script:
    - echo change to "npm run deploy:staging"
  environment:
    name: staging
    url: http://spark.int.daftup.com
  only:
    - master

deploy_production:
  stage: deploy
  before_script: *before_deploy
  script:
    - echo change to "npm run deploy:production"
  environment:
    name: production
    url: http://spark.daftup.com
  when: manual
  only:
    - master
