image: node:alpine

test:
  stage: test
  script:
    - npm i
    - npm run test-ci
    - npm run lint

.deploy: &deploy
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add
    - npm i pm2

.deploy:staging:
  <<: *deploy
  script:
    - npm run deploy:staging
  only:
    - staging

.deploy:production:
  <<: *deploy
  script:
    - npm run deploy:production
  only:
    - master
